name: Build and push Docker image

on:
  push:
    branches: ["main"]
    paths:
      - 'advanced-stack/**'

jobs: 
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code 
        uses: actions/checkout@v4

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ak099
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: build and push docker image
        uses: docker/build-push-action@v6
        with: 
          context: ./advanced-stack
          push: true
          tags: ak099/net-monitor:v1

  deploy: 
    needs: build-and-push
    runs-on: ubuntu:latest

    steps:
      - name: Deploy with SSH Action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}`
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu
            sudo docker pull web_app
            sudo docker compose up -d web_app
            
      - name: Deployment Summary
        run: |
          echo "🚀 Deployment Successful!"
          echo "Check the live app here: http://${{ secrets.ALB_URL }}"
